name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add a debug step to list files
      - name: Debug - List files
        run: ls -la
      
      # Add another debug step to show the GitHub Pages URL
      - name: Debug - Show GitHub Pages URL
        run: |
          echo "GitHub Pages URL: https://amelling.github.io/gif-spinner/"
          echo "Repository: ${{ github.repository }}"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .